<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHkr5QOr\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHkr5QOr/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHkr5QOr.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHkr5QOr\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHkr5QOr\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Hkr5QOr',
    'container.build_id' => '2265425b',
    'container.build_time' => 1570030997,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHkr5QOr');
