<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOmItByu\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOmItByu/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOmItByu.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOmItByu\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerOmItByu\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'OmItByu',
    'container.build_id' => 'f9bd88a3',
    'container.build_time' => 1570117206,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOmItByu');
