<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAEmaeDQ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAEmaeDQ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAEmaeDQ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAEmaeDQ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerAEmaeDQ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'AEmaeDQ',
    'container.build_id' => '24cb516b',
    'container.build_time' => 1570444155,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAEmaeDQ');
